language: java

jdk: 
   - oraclejdk8

script: mvn clean install

notifications:
    email:
       - poojagarwal.027@gmail.com
       - karasatishkumar@gmail.com
    on_success: always
    on_failure: always
    
deploy:
  provider: releases
  api_key:  920403cdba717d89b2662b144aef97d8433febc1
  file: target/bookstore-1.0.0-SNAPSHOT.war
  skip_cleanup: true
  on:
    tags: true
    
